/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfacez;

import Calificaciones.Nota1;
import Interfacez.FrmMatriculas;
import Interfacez.FrmListarDocentes;
import Interfacez.FrmListarCursos;
import Interfacez.FrmListarAlumnos;
import Interfacez.FrmConsultarAlumno;
import Interfacez.FrmAgregarDocente;
import Interfacez.FrmAgregarCurso;
import Interfacez.FrmAgregarAlumno;
import javax.swing.JOptionPane;

/**
 *
 * @author 
 */
public class FrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMAlumnos = new javax.swing.JMenu();
        jMAAgregar = new javax.swing.JMenuItem();
        jMAConsultar = new javax.swing.JMenuItem();
        jMAListar = new javax.swing.JMenuItem();
        jMDocentes = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMDListar = new javax.swing.JMenuItem();
        jMCursos = new javax.swing.JMenu();
        jMCAgregar = new javax.swing.JMenuItem();
        jMCListar = new javax.swing.JMenuItem();
        jMMatriculas = new javax.swing.JMenu();
        jMMAgregar = new javax.swing.JMenuItem();
        jMMatriculas1 = new javax.swing.JMenu();
        jMMAgregar1 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMSalir = new javax.swing.JMenuItem();

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/colegio/Imagenes/video-fondo-azul-_online-video-cutter.com_.gif"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("APLICACIÓN COLEGIO ADSI 1438222");
        setBackground(new java.awt.Color(153, 153, 255));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/colegio/Imagenes/logo-college-removebg-preview.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 41, 346, 307));

        jPanel1.setBackground(new java.awt.Color(0, 0, 204));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 855, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/colegio/Imagenes/Imagen inicio.jpeg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(353, 7, -1, 372));

        jLabel4.setBackground(new java.awt.Color(102, 255, 102));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 350));

        jLabel5.setBackground(new java.awt.Color(204, 204, 255));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 380));

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));
        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuBar1.setMinimumSize(new java.awt.Dimension(0, 4));

        jMAlumnos.setBackground(new java.awt.Color(255, 255, 255));
        jMAlumnos.setText("Alumnos");
        jMAlumnos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jMAAgregar.setText("Agregar alumno");
        jMAAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMAAgregarActionPerformed(evt);
            }
        });
        jMAlumnos.add(jMAAgregar);

        jMAConsultar.setText("Consultar alumno");
        jMAConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMAConsultarActionPerformed(evt);
            }
        });
        jMAlumnos.add(jMAConsultar);

        jMAListar.setText("Listado de alumnos");
        jMAListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMAListarActionPerformed(evt);
            }
        });
        jMAlumnos.add(jMAListar);

        jMenuBar1.add(jMAlumnos);

        jMDocentes.setBackground(new java.awt.Color(255, 255, 255));
        jMDocentes.setText("Docentes");
        jMDocentes.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jMenuItem1.setText("Agregar docente");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMDocentes.add(jMenuItem1);

        jMDListar.setText("Listado de docente");
        jMDListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMDListarActionPerformed(evt);
            }
        });
        jMDocentes.add(jMDListar);

        jMenuBar1.add(jMDocentes);

        jMCursos.setBackground(new java.awt.Color(255, 255, 255));
        jMCursos.setText("Asignaturas");
        jMCursos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jMCAgregar.setText(" Agregar asignatura");
        jMCAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMCAgregarActionPerformed(evt);
            }
        });
        jMCursos.add(jMCAgregar);

        jMCListar.setText("Listado de asignaturas");
        jMCListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMCListarActionPerformed(evt);
            }
        });
        jMCursos.add(jMCListar);

        jMenuBar1.add(jMCursos);

        jMMatriculas.setBackground(new java.awt.Color(255, 255, 255));
        jMMatriculas.setText("Matriculas");
        jMMatriculas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jMMAgregar.setText("Agregar");
        jMMAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMMAgregarActionPerformed(evt);
            }
        });
        jMMatriculas.add(jMMAgregar);

        jMenuBar1.add(jMMatriculas);

        jMMatriculas1.setBackground(new java.awt.Color(255, 255, 255));
        jMMatriculas1.setText("Calificaciones");
        jMMatriculas1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jMMAgregar1.setText("Registro de calificaciones");
        jMMAgregar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMMAgregar1ActionPerformed(evt);
            }
        });
        jMMatriculas1.add(jMMAgregar1);

        jMenuBar1.add(jMMatriculas1);

        jMenu1.setBackground(new java.awt.Color(255, 255, 255));
        jMenu1.setText("Cerrar");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jMSalir.setText("Salir");
        jMSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMSalirActionPerformed(evt);
            }
        });
        jMenu1.add(jMSalir);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMAAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMAAgregarActionPerformed
        // TODO add your handling code here:
        FrmAgregarAlumno frm = new FrmAgregarAlumno();
        frm.setVisible(true);
    }//GEN-LAST:event_jMAAgregarActionPerformed

    private void jMAListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMAListarActionPerformed
        // TODO add your handling code here:
        FrmListarAlumnos frm = new FrmListarAlumnos();
        frm.setVisible(true);
    }//GEN-LAST:event_jMAListarActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        FrmAgregarDocente frm = new FrmAgregarDocente();
        frm.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMCAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMCAgregarActionPerformed
        // TODO add your handling code here:
        FrmAgregarCurso frm = new FrmAgregarCurso();
        frm.setVisible(true);
    }//GEN-LAST:event_jMCAgregarActionPerformed

    private void jMCListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMCListarActionPerformed
        // TODO add your handling code here:
        FrmListarCursos frm = new FrmListarCursos();
        frm.setVisible(true);
    }//GEN-LAST:event_jMCListarActionPerformed

    private void jMDListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMDListarActionPerformed
        // TODO add your handling code here:
        FrmListarDocentes frm = new FrmListarDocentes();
        frm.setVisible(true);
    }//GEN-LAST:event_jMDListarActionPerformed

    private void jMAConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMAConsultarActionPerformed
        // TODO add your handling code here:
        FrmConsultarAlumno frm = new FrmConsultarAlumno();
        frm.setVisible(true);
    }//GEN-LAST:event_jMAConsultarActionPerformed

    private void jMSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMSalirActionPerformed
        // TODO add your handling code here:
     int confirmado = JOptionPane.showConfirmDialog(null, "Está seguro de Salir");
     if (JOptionPane.OK_OPTION==confirmado){
         System.exit(0);
     }
    }//GEN-LAST:event_jMSalirActionPerformed

    private void jMMAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMMAgregarActionPerformed
        // TODO add your handling code here:
        FrmMatriculas frm = new FrmMatriculas();
        frm.setVisible(true);
    }//GEN-LAST:event_jMMAgregarActionPerformed

    private void jMMAgregar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMMAgregar1ActionPerformed
        // TODO add your handling code here:
         new Nota1().setVisible(true);
    }//GEN-LAST:event_jMMAgregar1ActionPerformed

     public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAgregarAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAgregarAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAgregarAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAgregarAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuItem jMAAgregar;
    private javax.swing.JMenuItem jMAConsultar;
    private javax.swing.JMenuItem jMAListar;
    private javax.swing.JMenu jMAlumnos;
    private javax.swing.JMenuItem jMCAgregar;
    private javax.swing.JMenuItem jMCListar;
    private javax.swing.JMenu jMCursos;
    private javax.swing.JMenuItem jMDListar;
    private javax.swing.JMenu jMDocentes;
    private javax.swing.JMenuItem jMMAgregar;
    private javax.swing.JMenuItem jMMAgregar1;
    private javax.swing.JMenu jMMatriculas;
    private javax.swing.JMenu jMMatriculas1;
    private javax.swing.JMenuItem jMSalir;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
